[package]
name = "seferize_core"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0.106", features = ["full"] }
quote = "1.0.41"
proc-macro2 = "1.0.101"
seferize = "1.2.2"
rstest = "0.26.1"